apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: fapi
spec:
  selector:
    app: fastapi-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 8000 
