#https://forums.rancher.com/t/lb-ip-exposed-not-accessible/39604/3
#https://github.com/metallb/metallb/issues/1154

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2adv
  namespace: metallb-system
spec:
  ipAddressPools:
  - first-pool
